CREATE DATABASE sozdb;
CREATE USER 'lnkoc'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON `sozdb`.* TO 'lnkoc'@'localhost';
FLUSH PRIVILEGES;
USE sozdb;
CREATE TABLE ORGANIZATOR(
  ORGANIZATOR_ID INT(11) NOT NULL AUTO_INCREMENT,
  LOGIN VARCHAR(20) NOT NULL,
  HASLO VARCHAR(20) NOT NULL,
  IMIE VARCHAR(20) NOT NULL,
  NAZWISKO VARCHAR(25) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  ORGANIZACJA VARCHAR(255),
  TELEFON VARCHAR(15),
  CONSTRAINT organizator_pk PRIMARY KEY (ORGANIZATOR_ID)
);
CREATE TABLE SESJA(
  SESJA_ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  LOGIN VARCHAR(20) NOT NULL,
  TOKEN VARCHAR(30) NOT NULL,
  DATA_UTWORZENIA DATE NOT NULL
);
